package csii.dzip.core;

/**
 * Auto create from dictionary properties files.
 * every item in properties has Format like this:
 * key=comment<0:on;1:off>

 * Creation date: (Wed Oct 27 10:49:31 CST 2010)
 * @author: CSII PowerEngine $Auto Generated$
 */
public class Dict {
    public static final String ACCI_D1="ACCID1";            //Fix8583:102#帐户标识1
    public static final String ACCI_D2="ACCID2";            //Fix8583:103#帐户标识2
    public static final String ACCIDE_N1="ACCIDEN1";        //ISO8583:102# 账户标识1
    public static final String ACCIDE_N2="ACCIDEN2";        //ISO8583:103# 账户标识2
    public static final String ACQCODE="ACQCODE";           //ISO8583:32# 受理行分行编号
    public static final String ACQRESERVE="ACQRESERVE";     //ISO8583:122# 受理方保留
    public static final String ACQU="ACQU";                 //Fix8583:32#收理机构标识码
    public static final String ADDDATA="ADDDATA";           //ISO8583:44# 附加数据
    public static final String ADDDATAPRI="ADDDATAPRI";     //ISO8583:48# 附加数据
    public static final String ADDI="ADDI";                 //Fix8583:48#附加数据
    public static final String AMT="AMT";                   //Fix8583:4#交易金额
    public static final String AUTH="AUTH";                 //Fix8583:38#授权码
    public static final String AUTRESCOD="AUTRESCOD";       //ISO8583:38# 预授权码
    public static final String ACCT_BALENCE="AcctBalence";  //帐户余额
    public static final String BALAMT="BALAMT";             //ISO8583:54# 实际余额
    public static final String BANKID="BANKID";             //Fix8583:bankid#行号编号
    public static final String CACC="CACC";                 //Fix8583:#受理方编号
    public static final String CAID="CAID";                 //Fix8583:42#受卡方标识码
    public static final String CANL="CANL";                 //Fix8583:43#受卡方名称地址
    public static final String CARDACCCODE="CARDACCCODE";   //ISO8583:42# 受卡方标识码
    public static final String CARDACCID="CARDACCID";       //ISO8583:41# 终端号
    public static final String CARDACCNAME="CARDACCNAME";   //ISO8583:43# 受卡方名称地址
    public static final String CATI="CATI";                 //Fix8583:41#受卡方终端标识
    public static final String CURCODE="CURCODE";           //ISO8583:49# 币种
    public static final String CARD_ACCEPTORID_CODE="CardAcceptorIDCode";       //coreProXML:受卡方标识码
    public static final String CHANNEL_CODE="ChannelCode";  //渠道代码;
    public static final String CONT_CTRL="ContCtrl";        //coreProXML:暂未用到
    public static final String DEST="DEST";                 //Fix8583:100#接收机构标识码
    public static final String EXPDAT="EXPDAT";             //ISO8583:14# 卡有效期
    public static final String EXPI="EXPI";                 //Fix8583:14#卡有效期
    public static final String FEE="FEE";                   //Fix8583:28#交易费
    public static final String FORW="FORW";                 //Fix8583:333#发送机构标识码
    public static final String FORWARDCODE="FORWARDCODE";   //ISO8583:33# 总行编号
    public static final String FILE_UPDATE_CODE="FileUpdateCode";               //coreProXML:暂未用到
    public static final String HEADER_ATM="Header_ATM";     //coreProXML:暂未用到
    public static final String IDEN="IDEN";                 //Fix8583:61#持卡人身份认证信息
    public static final String IDENNUMBE="IDENNUMBE";       //ISO8583:61# 证件编号
    public static final String IS_S1="ISS1";                //Fix8583:#发卡行1编号
    public static final String IS_S2="ISS2";                //Fix8583:#发卡行2编号
    public static final String ISURESERVE="ISURESERVE";     //ISO8583:123# 发卡方保留
    public static final String LOCD="LOCD";                 //Fix8583:13#受卡方所在地日期
    public static final String LOCT="LOCT";                 //Fix8583:12#受卡方所在地时间
    public static final String LOCTRANSDATE="LOCTRANSDATE"; //ISO8583:13# 交易日期
    public static final String LOCTRANSTIME="LOCTRANSTIME"; //ISO8583:12# 交易时间
    public static final String MAC="MAC";                   //Fix8583:#MAC
    public static final String MERC="MERC";                 //Fix8583:18# 商户类型
    public static final String MERCHANTTYPE="MERCHANTTYPE"; //ISO8583:18# 商户类型
    public static final String MESAUTHCD="MESAUTHCD";       //ISO8583:128#MAC
    public static final String MESG="MESG";                 //Fix8583:MSG#消息类型
    public static final String MSG_FLAG="MsgFlag";          //报文标识;
    public static final String MSG_ID="MsgId";              //报文标识号;
    public static final String MSG_LEN="MsgLen";            //报文长度;
    public static final String MSG_TYPE="MsgType";          //coreProXML:报文种类
    public static final String NAICS_CODE="NAICSCode";      //coreProXML:
    public static final String NANSCRESERVE="NANSCRESERVE"; //ISO8583:121# CUPS 保留
    public static final String NETWORK_DATA="NetworkData";  //coreProXML:网络工作日期
    public static final String ORGDATA="ORGDATA";           //ISO8583:90# 原交易信息
    public static final String ORIG="ORIG";                 //Fix8583:90#原始数据元
    public static final String OUTPUT_THEXM="OutputTheXM";  //coreProXML:暂未用到
    public static final String PAN="PAN";                   //Fix8583:2#主帐号
    public static final String PIN="PIN";                   //Fix8583:52#个人标识码数据
    public static final String PINDATA="PINDATA";           //ISO8583:52#卡密码
    public static final String POSC="POSC";                 //Fix8583:25#服务点条件码
    public static final String POSE="POSE";                 //Fix8583:22#服务点输入方式码
    public static final String POSP="POSP";                 //Fix8583:26#服务点PIN获取码
    public static final String PRIACCNUM="PRIACCNUM";       //ISO8583:2# 卡号
    public static final String PROC="PROC";                 //Fix8583:3#处理码
    public static final String PROCOD="PROCOD";             //ISO8583:3# 处理码
    public static final String PINNEDYN="PinnedYN";         //coreProXML:是否使用密码
    public static final String PROC_CODE="ProcCode";        //coreProXML:交易码
    public static final String RCVCODE="RCVCODE";           //ISO8583:100# 接收方机构码
    public static final String REACODE="REACODE";           //ISO8583:60# 自定义域
    public static final String RESCODE="RESCODE";           //ISO8583:39# 响应码
    public static final String RESE="RESE";                 //Fix8583:60#自定义域
    public static final String RESP="RESP";                 //Fix8583:39#应答码
    public static final String RETR="RETR";                 //Fix8583:37#索引参考号
    public static final String RETU="RETU";                 //Fix8583:54#实际余额
    public static final String RTVREFNUM="RTVREFNUM";       //ISO8583:37# 检索参考号
    public static final String RSP_MSG="RspMsg";            //响应信息;
    public static final String SECU="SECU";                 //Fix8583:53#安全控制信息
    public static final String SERCAPCODE="SERCAPCODE";     //ISO8583:26# 服务点PIN获取码
    public static final String SERCONDCODE="SERCONDCODE";   //ISO8583:25# 服务点条件码不用处理
    public static final String SERENTRYMODE="SERENTRYMODE"; //ISO8583:22# 服务点输入方式
    public static final String SETDATE="SETDATE";           //ISO8583:15# 清算日期
    public static final String SETT="SETT";                 //Fix8583:15#清算日期
    public static final String SIC_CODE="SICCode";          //coreProXML:跟踪代码
    public static final String SICSUB_CODE="SICSUBCode";    //coreProXML:跟踪子代码
    public static final String SYSTRACENUM="SYSTRACENUM";   //ISO8583:11# 系统跟踪号
    public static final String SEND_TIME="SendTime";        //发送时间;
    public static final String SETTLE_DATE="SettleDate";    //coreProXML:清算日期
    public static final String SYSTEM_TRACE_NUMBER="SystemTraceNumber";         //coreProXML:暂未用到
    public static final String TRAC="TRAC";                 //Fix8583:11#系统跟踪号
    public static final String TRAC_K2="TRACK2";            //Fix8583:35#第二磁道信息
    public static final String TRAC_K2DATA="TRACK2DATA";    //ISO8583:25# 第二磁道
    public static final String TRAC_K3="TRACK3";            //Fix8583:36#第三磁道信息
    public static final String TRAC_K3DATA="TRACK3DATA";    //ISO8583:36# 第三磁道
    public static final String TRANSAMT="TRANSAMT";         //ISO8583:4# 交易金额
    public static final String TRANSDTTIME="TRANSDTTIME";   //ISO8583:7# 主机系统时间
    public static final String TRANSFEE="TRANSFEE";         //ISO8583:28# 交易手续费
    public static final String TRCU="TRCU";                 //Fix8583:49#交易货币代码
    public static final String TRDT="TRDT";                 //Fix8583:7#传输日期和时间
    public static final String TRAN_AMT="TranAmt";          //交易金额
    public static final String TRAN_CODE="TranCode";        //交易码;
    public static final String TRANSAC_ACCNT_FROM="TransacAccntFrom";           //coreProXML:转出帐户
    public static final String TRANSAC_ACCNT_TO="TransacAccntTo";               //coreProXML:转入帐户
    public static final String TRANSAC_ACQUIRERID_CODE="TransacAcquirerIDCode"; //coreProXML:暂未用到
    public static final String TRANSAC_AMOUNT="TransacAmount";                  //coreProXML:交易金额
    public static final String TRANSAC_AUDIT_TRACE="TransacAuditTrace";         //coreProXML:跟踪稽查
    public static final String TRANSAC_CARD_SEQ_NUM="TransacCardSeqNum";        //coreProXML:暂未用到
    public static final String TRANSAC_FEE_AMOUNT="TransacFeeAmount";           //coreProXML:手续费
    public static final String TRANSACISO_ALPHA_COUNTRY_CODE="TransacISOAlphaCountryCode";          //coreProXML:暂未用到
    public static final String TRANSAC_INSTITUTION_MERCHANT_NAME="TransacInstitutionMerchantName";  //coreProXML:商户名称
    public static final String TRANSAC_LOCAL_DATE="TransacLocalDate";           //coreProXML:本地日期
    public static final String TRANSAC_LOCAL_DATE_TIME="TransacLocalDateTime";  //coreProXML:交易日期时间
    public static final String TRANSAC_LOCATION_CITY="TransacLocationCity";     //coreProXML:暂未用到
    public static final String TRANSAC_LOCATION_STATE="TransacLocationState";   //coreProXML:暂未用到
    public static final String TRANSAC_LOCATION_STREET_ADDRESS="TransacLocationStreetAddress";      //coreProXML:受卡方地址
    public static final String TRANSAC_MANAGECD="TransacManageCD";              //coreProXML:暂未用到
    public static final String TRANSAC_MANAGE_DATA="TransacManageData";         //coreProXML:暂未用到
    public static final String TRANSAC_PAN="TransacPan";    //coreProXML:卡号
    public static final String TRANSAC_RETRIEVAL_REF_NUM="TransacRetrievalRefNum";                  //coreProXML:系统参考号
    public static final String TRANSAC_REVERSAL_AMOUNT="TransacReversalAmount"; //coreProXML:冲正金额
    public static final String TRANSAC_RSN_CODE="TransacRsnCode";               //coreProXML:暂未用到
    public static final String TRANSAC_STATEMENT_TYPE="TransacStatementType";   //coreProXML:暂未用到
    public static final String TRANSAC_SWITCH_DATE="TransacSwitchDate";         //coreProXML:本地日期
    public static final String TRANSAC_TERMINALID="TransacTerminalID";          //coreProXML:终端号
    public static final String TRANSAC_TRACK2_DATA="TransacTrack2Data";         //coreProXML:二磁信息
    public static final String WORK_DATE="WorkDate";        //工作日期;
    public static final String IN__TRAN_CODE="in_TranCode"; //内部交易码（核心存储过程）
    public static final String IN_XML_CNT="in_XMLCnt";      //传入报文组数
    public static final String OUT_XML="out_XML";           //核心存储过程返回报文
    public static final String OUT_XML_CNT="out_XMLCnt";    //返回报文组数

    public static final String IBS_TIME_STAMP = "IBSTrsTimestamp";//PE时间戳标签名
    /**T_ICCLOSINGPAY*/
    public static final String CARD_NO = "Card_No"; //卡号
    public static final String TRXTYPE = "TrxType";	//交易代码
    public static final String ACTCODE = "ActCode"; //动作代码
    public static final String REGDATE = "RegDate"; //登记日期
    public static final String LGNTYPE = "LgnType"; //登记身份类型
    public static final String RETCODE = "RetCode";	//返回值
    public static final String LGNINSTCODE = "LgnInstCode"; //登录机构代码
    public static final String SOURCE = "Source"; //交易来源：BP柜面
    public static final String TRACENO = "TraceNo"; //系统跟踪号
    public static final String LGNMERCHCODE = "LgnMerchCode"; //登录网点代码
    public static final String LGNUSERCODE = "LgnSerCode"; //登录操作员代码
    public static final String RTNWAY = "RtnWay"; //IC卡余额退还方式
    public static final String NAMEFLAG = "NameFlag"; //是否验证客户信息
    public static final String ID_TYPE = "Id_Type"; //证件类型
    public static final String ID_CODE = "Id_Code"; //证件号码
    public static final String PINFLAG = "PinFlag"; //是否验证密码
    public static final String RTNFLG = "RtnFlag"; //是否回收卡片
    public static final String TRANNO = "TranNo"; //交易流水号
    public static final String FIR_CUR = "Fir_Cur"; //主币种
    public static final String FIR_AMOUNT = "Fir_Amount"; //主币种账户返回金额
    public static final String SEC_CUR = "Sec_Cur"; //次币种
    public static final String SEC_AMOUNT = "Sec_Amount"; //次币种账户返回金额
    public static final String RESERVED = "Reserved"; //保留域
    public static final String LASTMAINTDATE = "LastMaintDate"; //最后维护日期
    public static final String INSTNO = "InstNo";	//机构号
    public static final String TRANSEQ = "TranSeq";	//流水号
    public static final String TRANTIME = "TranTime";	//交易时间
    public static final String RSPNO = "RspNo";	//交易应答码
    public static final String ICDATA = "ICData";	//IC卡数据域
    public static final String ICDATALENGTH = "ICDataLength";	//IC卡数据域

    public static final String SOURCE_BP = "BP";//交易来源：柜面
    public static final String PE_TP = "TP";//证件类型用于替换组装的61#的1-2位证件类型
    public static final String PE_ID_CODE = "IDCODE";//证件号码用于替换组装的61#证件号码
    public static final String IDENUMBER_X = "X";//身份证号码中的X
    /**调用前置存储过程参数名*/
    public static final String IN_CARD_NO = "in_CARD_No"; //卡号
    public static final String IN_TRXTYPE = "in_TrxType"; //交易代码
    public static final String IN_ACTCODE = "in_ActCode"; //动作代码
    public static final String IN_LGNTYPE = "iN_LgnType"; //登录类型
    public static final String IN_SOURCE = "in_Source"; //交易来源
    public static final String IN_LGNINSTCODE = "in_LgnInstCode"; //登录机构代码
    public static final String IN_TRACENO = "in_TraceNo"; //系统跟踪号
    public static final String IN_LGNMERCHCODE = "in_LgnMerchCode"; //登录网点代码
    public static final String IN_LGNUSRECODE = "in_LgnUserCode"; //登录柜员代码
    public static final String IN_RTNWAY = "in_RtnWay"; //卡片余额退还方式
    public static final String IN_NAMEFLAG = "in_NameFlag"; //是否验证客户信息
    public static final String IN_ID_TYPE = "in_Id_Type"; //证件类型
    public static final String IN_ID_CODE = "in_Id_Code"; //证件号码
    public static final String IN_PINFLAG = "in_PinFlag"; //是否验证密码
    public static final String IN_RTNFLG = "in_RtnFlg"; //卡片是否回收
    public static final String OUT_ERRORNBR = "out_ERRORNBR" ;              //错误码
	public static final String OUT_ERRORMSG = "out_ERRORMSG" ;              //错误信息
}
